# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fbossio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: starwars-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: starwars

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TableName: ${self:service}-missions
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Scan
      - dynamodb:DescribeTable
    Resource:
      - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-missions

functions:  
  planets:
    handler: handler.getPlanets
    events:
      - http:
          path: /planets
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  planetById:
    handler: handler.getPlanet
    events:
      - http:
          path: /planets/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  people:
    handler: handler.getPeople
    events:
      - http:
          path: /people
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  personById:
    handler: handler.getPerson
    events:
      - http:
          path: /people/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  films:
    handler: handler.getFilms
    events:
      - http:
          path: /films
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  filmById:
    handler: handler.getFilm
    events:
      - http:
          path: /films/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  getMissions:
    handler: handler.listMissions
    events:
      - http:
          path: /missions
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getMission:
    handler: handler.getMission
    events:
      - http:
          path: /missions/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  createMission:
    handler: handler.createMission
    events:
      - http:
          path: /missions
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  swaggerUI:
    handler: functions/swagger.swaggerUI
    events:
      - http:
          path: docs
          method: get
          cors: true
  getSwaggerDocument:
    handler: functions/swagger.getSwaggerDocument
    events:
      - http:
          path: docs/swagger.yaml
          method: get
          cors: true

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-missions
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package: 
  include:
    - swagger.yaml
