# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fbossio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: starwars-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: starwars

provider:
  name: aws
  runtime: nodejs20.x

functions:  
  planets:
    handler: handler.getPlanets
    events:
      - httpApi:
          path: /planets
          method: get
  people:
    handler: handler.getPeople
    events:
      - httpApi:
          path: /people
          method: get
  films:
    handler: handler.getFilms
    events:
      - httpApi:
          path: /films
          method: get
  getMissions:
    handler: handler.getMissions
    events:
      - httpApi:
          path: /missions
          method: get
  createMission:
    handler: handler.createMission
    events:
      - httpApi:
          path: /missions
          method: post

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-missions
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
