openapi: 3.0.0
info:
  title: Star Wars API
  description: API para gestionar misiones y obtener recursos de Star Wars.
  version: '1.0.0'
paths:
  /planets:
    get:
      summary: Lista los planetas
      responses:
        '200':
          description: OK
  /missions:
    get:
      summary: Lista las misiones
      responses:
        '200':
          description: OK